name: build-docs-actions
run-name: building docs
on:
  push
  # push:
  #   branches:
  #     - main
jobs:
  find-provider-on-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: find updated providers
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./ci-scripts/get-netlify-vars.js')
            await script({github, context, core})


      # - name: Get Provider name
      #   uses: actions/github-script@v6
      #   env:
      #     PROVIDERS: ${{ env.PROVIDERS }}
      #   with:
      #     script: |
      #       console.log(process.env.PROVIDERS)
      #       const script = require('./.github/workflows/get-netlify-vars.js')
      #       await script({github, context, core})