name: build-docs-actions
run-name: building docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  find-provider-on-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: find changed files
        run: cd $GITHUB_WORKSPACE; git diff-tree --no-commit-id --name-only -r $GITHUB_SHA > diff.txt

      - name: find updated providers
        run: |
          cat diff.txt
          allproviders=()
          uniqproviders=()
          while IFS="" read -r p || [ -n "$p" ]
          do
            if [[ $p == docs/*/providers/* ]]; then
              provider="$(echo $p | cut -d'/' -f4)"
              allproviders+=( $provider )
            fi
          done < diff.txt
          rm diff.txt
          uniqproviders=($(for i in "${allproviders[@]}"; do echo "${i}"; done | sort -u))
          providers=$( printf '%s' "${uniqproviders[@]}" )
          echo $providers
          echo "PROVIDERS=$(echo $providers)" >> $GITHUB_ENV


      - name: Get Provider name
        uses: actions/github-script@v6
        env:
          PROVIDERS: ${{ env.PROVIDERS }}
        with:
          script: |
            console.log(process.env.PROVIDERS)
            const script = require('./.github/workflows/get-netlify-vars.js')
            await script({github, context, core})