name: build-docs-actions
run-name: building docs
on:
  # push:
  #   branches:
  #     - main
  pull_request: ## TODO: remove this and only leave push main after finished testing
    branches:
      - main

jobs:
  find-provider-on-change:
    runs-on: ubuntu-latest
    outputs: 
      providers: ${{ steps.provider-to-deploy.outputs.provider_to_deploy }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: find updated providers
        id: provider-to-deploy
        uses: actions/github-script@v6
        env: 
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          script: |
            const script = require('./ci-scripts/get-netlify-vars.js')
            await script({github, context, core})

      - name: show updated providers
        env: 
          PROVIDERS_TO_DEPLOY: ${{ steps.provider-to-deploy.outputs.provider_to_deploy }}
        run:
          echo "find updated providers -> ${PROVIDERS_TO_DEPLOY}"
  
  deploy-to-netlify:
    runs-on: ubuntu-latest
    needs: find-provider-on-change
    strategy:
      fail-fast: false
      matrix:
        provider: ${{fromJson(needs.find-provider-on-change.outputs.providers)}}

    steps:
      - name: show updated providers in matrix
        id: set-keys
        env: 
          PROVIDER_TO_DEPLOY: ${{ matrix.provider }}
        run:
          PROVIDER_TO_DEPLOY_UPPER="$(echo "$PROVIDER_TO_DEPLOY" | awk '{print toupper($0)}')"
          echo "Deploy $PROVIDER_TO_DEPLOY_UPPER"
          echo "key name is NETLIFY_SITE_ID_$PROVIDER_TO_DEPLOY_UPPER"
          echo "::set-output name=netlify_site_id_key::NETLIFY_SITE_ID_$PROVIDER_TO_DEPLOY_UPPER"


      - name: Publish
        # uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: '${{ secrets[steps.set-keys.outputs.netlify_site_id_key] }}'
          NETLIFY_BASE: site
          NETLIFY_CMD: npm build
          NETLIFY_DIR: site/_build
        run:
          echo "After concat is ${NETLIFY_SITE_ID}"




      # - name: Get Provider name
      #   uses: actions/github-script@v6
      #   env:
      #     PROVIDERS: ${{ env.PROVIDERS }}
      #   with:
      #     script: |
      #       console.log(process.env.PROVIDERS)
      #       const script = require('./.github/workflows/get-netlify-vars.js')
      #       await script({github, context, core})