name: build-docs-actions
run-name: building docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy-netlify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter-changed-provider
      with:
        filters: |
          aws:
            - 'docs/aws-docs/**'
          azure:
            - 'docs/azure-docs/**'

    - name: Get Provider name
      uses: actions/github-script@v6
      env:
        PROVIDER_CHANGED: ${{ steps.filter-changed-provider.outputs }}
      with:
        script: |
          console.log(process.env.PROVIDER_CHANGED)
          // const script = require('./.github/workflows/get-netlify-vars.js')
          // await script({github, context, core, ${{ steps.find-provider-on-change.outputs}}})