name: build-docs-actions
run-name: building docs
on:
  # push:
  #   branches:
  #     - main
  # Compare the last commit of main -> to the current commit of a PR branch. 
  # (Note: To compare changes between the last pushed commit to the remote PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - main

jobs:
  find-provider-on-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35


      - name: find changed files
        run: cd $GITHUB_WORKSPACE; git diff-tree --no-commit-id --name-only -r $GITHUB_SHA > diff.txt

      - name: find updated providers
        uses: actions/github-script@v6
        env: 
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          script: |
            const script = require('./ci-scripts/get-netlify-vars.js')
            await script({github, context, core})


      # - name: Get Provider name
      #   uses: actions/github-script@v6
      #   env:
      #     PROVIDERS: ${{ env.PROVIDERS }}
      #   with:
      #     script: |
      #       console.log(process.env.PROVIDERS)
      #       const script = require('./.github/workflows/get-netlify-vars.js')
      #       await script({github, context, core})