name: build-docs-actions
run-name: building docs
on:
  # push:
  #   branches:
  #     - main
  pull_request: ## TODO: remove this and only leave push main after finished testing
    branches:
      - main

jobs:
  find-provider-on-change:
    runs-on: ubuntu-latest
    outputs: 
      providers: ${{ steps.provider-to-deploy.outputs.provider_to_deploy }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: find updated providers
        id: provider-to-deploy
        uses: actions/github-script@v6
        env: 
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          script: |
            const script = require('./ci-scripts/get-netlify-vars.js')
            await script({github, context, core})

      - name: show updated providers
        env: 
          PROVIDERS_TO_DEPLOY: ${{ steps.provider-to-deploy.outputs.provider_to_deploy }}
        run:
          echo "find updated providers -> ${PROVIDERS_TO_DEPLOY}"

  install: 
    runs-on: ubuntu-latest
    needs: find-provider-on-change

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install
        run:
          npm install

  deploy-to-netlify:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        provider: ${{fromJson(needs.find-provider-on-change.outputs.providers)}}

    steps:
      - name: show updated providers in matrix
        id: set-keys
        if: ${{ matrix.provider == 'aws' }}
        env: 
          PROVIDER_TO_DEPLOY: ${{ matrix.provider }}
        run:
          PROVIDER_NAME="$(echo "$PROVIDER_TO_DEPLOY")"

          echo "Deploy $PROVIDER_NAME"
          echo "key name is NETLIFY_SITE_ID_$PROVIDER_NAME"
          echo "::set-output name=netlify_site_id_key::NETLIFY_SITE_ID_$PROVIDER_NAME"

      - name: Checkout
        uses: actions/checkout@v2

      
      - name: Build
        run: npm run build:${{matrix.provider}}


      - name: Publish
        uses: netlify/actions/cli@master
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets[format('NETLIFY_SITE_ID_{0}', matrix.provider)] }}
          NETLIFY_BASE: site
          NETLIFY_CMD: ${{ format('npm run build::{0}', matrix.provider) }}
          NETLIFY_DIR: site/_build
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --prod --dir ./build




      # - name: Get Provider name
      #   uses: actions/github-script@v6
      #   env:
      #     PROVIDERS: ${{ env.PROVIDERS }}
      #   with:
      #     script: |
      #       console.log(process.env.PROVIDERS)
      #       const script = require('./.github/workflows/get-netlify-vars.js')
      #       await script({github, context, core})